spring:
  application:
     name: parkiMeterPro
  profiles: 
     active: 'local'
  data:
    mongodb:
      uri: ${MONGODB_URL}
      database: ${MONGODB_DATABASE}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
springdoc:
  swagger-ui:
    path: /swagger.html
gov:
  parking:
    taxas: 1.05
    each:
      hour: 3.00
    max:
      hours: 3
server:
   port: 9080