name: Deploy Application second-tech-challeng

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'
            - name: Build project
              run: mvn clean install -DskipTests
            - name: Login Docker Hub
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            - name: Build docker image
              run: docker build -t squadthreefiap/second-tech-challeng .
            - name: Push image docker
              run: docker push squadthreefiap/second-tech-challeng
            # Adjusted lines for MongoDB image
            - name: Build MongoDB docker image
              run: docker build -t squadthreefiap/second-tech-challengmongodb .
            - name: Push MongoDB docker image
              run: docker push squadthreefiap/second-tech-challeng-mongodb
